# Puerto del servidor
server.port=8001

# --- Base de datos ---
spring.datasource.url= ${DATABASE_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- Zona horaria ---
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.main.allow-bean-definition-overriding=true

# --- RabbitMQ ---
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=postgres
spring.rabbitmq.password=1234
spring.rabbitmq.stomp-port=61613
rabbitmq.queue.name=chat.default.queue

# --- Redis ---
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.cache.type=${REDIS_CACHE_TYPE}

# --- Capa de seguridad ---
jwt.secretKey=${JWT_SECRET_KEY}
jwt.expiration=${JWT_EXPIRATION_DATE}
